
export const cards_data = [
    {
        id: 1,
        category: "tecnologia",
        accentuated_category: "Tecnologia",
        image: "https://placehold.co/600x400/A7C7E7/000000?text=Tecnologia",
        title: "A Revolução da IA Generativa",
        description: "Descubra como a Inteligência Artificial está transformando a criação de conteúdo, arte e muito mais.",
        full_text: "A Inteligência Artificial Generativa, impulsionada por modelos de linguagem grandes (LLMs) e redes generativas adversariais (GANs), está redefinindo os limites da criatividade e automação. Desde a escrita de textos e roteiros até a geração de imagens realistas e composições musicais complexas, a IA generativa está se tornando uma ferramenta indispensável em diversas indústrias. Empresas de tecnologia estão investindo pesado nessa área, prometendo um futuro onde a colaboração entre humanos e máquinas será ainda mais fluida e produtiva.",
        date: new Date().toLocaleDateString(),
    },
    {
        id: 2,
        category: "moda",
        accentuated_category: "Moda",
        image: "https://placehold.co/600x400/DDA0DD/000000?text=Moda",
        title: "Tendências de Verão 2025",
        description: "Um guia completo com as cores, tecidos e estilos que dominarão a próxima estação.",
        full_text: "As tendências de verão para 2025 apontam para uma fusão de conforto e elegância. Veremos o retorno de cores vibrantes, como laranja queimado e verde-limão, combinadas com tons neutros. Tecidos leves e naturais como linho e algodão serão protagonistas, enquanto os cortes amplos e fluidos garantirão o bem-estar. Acessórios maxi, como óculos de sol oversized e bolsas de palha, complementarão os looks, trazendo um toque de sofisticação descontraída para a estação mais quente do ano.",
        date: new Date().toLocaleDateString(),
    },
    {
        id: 3,
        category: "inovacao",
        accentuated_category: "Inovação",
        image: "https://placehold.co/600x400/98FB98/000000?text=Inovação",
        title: "Startups que Estão Mudando o Mundo",
        description: "Conheça as empresas emergentes que estão revolucionando diversos setores da economia.",
        full_text: "O ecossistema de startups continua a ser um motor de inovação global. Empresas emergentes estão desafiando modelos de negócios tradicionais e apresentando soluções disruptivas em áreas como saúde digital, energia renovável e educação personalizada. Desde plataformas que conectam agricultores a tecnologias de ponta até aplicativos que democratizam o acesso à saúde mental, essas startups não estão apenas criando valor econômico, mas também gerando um impacto social significativo. A agilidade e a capacidade de adaptação são suas maiores forças.",
        date: new Date().toLocaleDateString(),
    },
    {
        id: 4,
        category: "agricultura",
        accentuated_category: "Agricultura",
        image: "https://placehold.co/600x400/B0E0E6/000000?text=Agricultura",
        title: "Agricultura 4.0: O Futuro no Campo",
        description: "Como a tecnologia está impulsionando a produtividade e a sustentabilidade no agronegócio.",
        full_text: "A Agricultura 4.0 representa a fusão de tecnologias digitais com a produção agrícola. Sensores inteligentes, drones, inteligência artificial e internet das coisas (IoT) estão sendo implementados para otimizar o uso de recursos, monitorar a saúde das plantações e prever rendimentos com maior precisão. Essa revolução tecnológica não só aumenta a produtividade e a eficiência, mas também promove práticas agrícolas mais sustentáveis, reduzindo o impacto ambiental e garantindo a segurança alimentar para as futuras gerações.",
        date: new Date().toLocaleDateString(),
    },
    {
        id: 5,
        category: "tecnologia",
        accentuated_category: "Tecnologia",
        image: "https://placehold.co/600x400/ADD8E6/000000?text=Ciberseguranca",
        title: "Cibersegurança: Protegendo Seus Dados",
        description: "As últimas tendências e melhores práticas para manter suas informações seguras no mundo digital.",
        full_text: "Em um mundo cada vez mais conectado, a cibersegurança tornou-se uma preocupação primordial para indivíduos e organizações. Ameaças como ransomware, phishing e ataques de dia zero estão em constante evolução, exigindo estratégias de defesa robustas e proativas. As melhores práticas incluem a implementação de autenticação multifator, treinamento de conscientização para usuários, uso de softwares de segurança atualizados e a adoção de políticas de privacidade rigorosas. Proteger seus dados é proteger seu futuro digital.",
        date: new Date().toLocaleDateString(),
    },
    {
        id: 6,
        category: "inovacao",
        accentuated_category: "Inovação",
        image: "https://placehold.co/600x400/FFD700/000000?text=Transportes+Urbanos",
        title: "O Futuro dos Transportes Urbanos",
        description: "Veículos autônomos, mobilidade elétrica e soluções inteligentes para as cidades do amanhã.",
        full_text: "As cidades do futuro serão moldadas por inovações radicais nos transportes. Veículos autônomos prometem reduzir o trânsito e acidentes, enquanto a mobilidade elétrica, com carros e bicicletas elétricas, visa diminuir a poluição do ar e sonora. Soluções inteligentes, como sistemas de transporte público integrados e aplicativos de compartilhamento de viagens, otimizarão os deslocamentos. A infraestrutura urbana também evoluirá para suportar essas novas modalidades, criando ambientes mais eficientes, verdes e agradáveis para viver.",
        date: new Date().toLocaleDateString(),
    },
];